# Generated by Django 5.2.6 on 2025-09-26 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('country', models.CharField(max_length=30, verbose_name='Страна')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, verbose_name='Имя Пользователя')),
                ('email', models.CharField(max_length=25, verbose_name='Электронная почта')),
                ('password_hash', models.CharField(verbose_name='Хэш пароля')),
                ('created_at', models.DateTimeField(verbose_name='Дата создания аккаунта')),
                ('is_admin', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(verbose_name='Дата добавления')),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_app.city')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateTimeField(verbose_name='Дата')),
                ('temperature_min', models.FloatField(verbose_name='Минимальная температура')),
                ('temperature_max', models.FloatField(verbose_name='Maксимальная температура')),
                ('condition', models.CharField(max_length=30, verbose_name='Погодные условия')),
                ('humidity', models.IntegerField(verbose_name='Влажность')),
                ('created_at', models.DateTimeField(verbose_name='Время создания')),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_app.city')),
            ],
        ),
    ]
