# Generated by Django 5.2.6 on 2025-09-30 11:03

import weather_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name_plural': 'Favorite Cities'},
        ),
        migrations.AddField(
            model_name='city',
            name='users',
            field=models.ManyToManyField(through='weather_app.Favorite', to='weather_app.user', verbose_name='Пользователи'),
        ),
        migrations.AlterField(
            model_name='city',
            name='latitude',
            field=models.FloatField(validators=[weather_app.validators.validate_latitude], verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='city',
            name='longitude',
            field=models.FloatField(validators=[weather_app.validators.validate_longitude], verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания аккаунта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=25, unique=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='weatherforecast',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
    ]
