# Generated by Django 5.2.6 on 2025-10-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0002_alter_city_options_alter_favorite_options_city_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='city_photos/', verbose_name='Фото города'),
        ),
    ]
