# Generated by Django 5.2.6 on 2025-10-20 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0003_city_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='city',
            name='users',
            field=models.ManyToManyField(through='weather_app.Favorite', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
