# Generated by Django 5.2.6 on 2025-11-04 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0007_supportrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name_plural': 'Cities'},
        ),
    ]
